#**Introduction to Python**

###Simple Mathematical Operation

In [2]:
#price of a zero coupon bond with principal of 100, yield of 5%, and time to maturity of 3years
100/(1+0.05)**4

82.27024747918819

###Concept of variable

In [12]:
principal = 100
time = 3
ytm = 0.05

price = principal/(1+ytm)**(time)

print(price)

86.3837598531476


In [18]:
maturity = float(input("Enter the time to maturity: "))
face = input("Enter the principal: ")
face = float(face)
yld = input("Enter the yield to maturity: ")
yld = float(yld)

fair_price = face/(1+yld)**maturity
print("Price = ",fair_price)

Enter the time to maturity: 3
Enter the principal: 100
Enter the yield to maturity: 0.03
Price =  91.51416593531596


###Concept of data type

In [15]:
a = 100
b = 0.1
# c = A will give an error (NameError: name 'A' is not defined). It treats A as a variable which has not been assigned any value 
c = "Arpit"
d = "10"
e = True
f = [2,3,1,"Arpit"]

print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'list'>


###Print statement

In [ ]:
print(price)
print("The price of the zero coupon bond is: ", price)
print("The price of the zero coupon bond truncated to 4 significant digits is: ","%.4f"% price)
print("The price of the zero coupon bond ignoring the fractional value is: ","%i"% price)
print("The price of the bond is ","%.2f"% price, " and the ytm is ", ytm)

86.3837598531476
The price of the zero coupon bond is:  86.3837598531476
The price of the zero coupon bond truncated to 4 significant digits is:  86.3838
The price of the zero coupon bond ignoring the fractional value is:  86
The price of the bond is  86.38  and the ytm is  0.05


###Typecasting

In [ ]:
a = 10
b = 20
c = a+b
print(c)
print(type(c))

30
<class 'int'>


In [ ]:
a = 10
b = 20.0
c = a+2*b
print("The value of c is: ", c)
#The line c = a+b above could have been avoided by incorporating that in the print statement like print("The value of c is: ", a+2*b)
print("The data type of c is: ", type(c))
d = a + int(b)
print("The value of d is: ",d)
print("The data type of d is: ", type(d))

#It should be obvious by now that a = "10", b = 20 would give an error for c = a+b

The value of c is:  50.0
The data type of c is:  <class 'float'>
The value of d is:  30
The data type of d is:  <class 'int'>


###User input

In [ ]:
#Note that the user input always results in a string output. Thus, we need to change it by typecasting based on the need.
'''
#This code will result in an error as the maturity, face, and yld are strings on which arithmetic operation is being performed
maturity = input("Enter the time to maturity: ")
face = input("Enter the principal: ")
yld = input("Enter the yield to maturity: ")
fair_price = face/(1+yld)**maturity
'''

#Below code has been commented so that run-all does not always stop at this point. Uncomment to demonstrate this and then comment again
'''
maturity = float(input("Enter the time to maturity: "))
face = float(input("Enter the principal: "))
yld = float(input("Enter the yield to maturity: "))
price = face/(1+yld)**maturity

print("The price is", price)
'''

'\nmaturity = float(input("Enter the time to maturity: "))\nface = float(input("Enter the principal: "))\nyld = float(input("Enter the yield to maturity: "))\nprice = face/(1+yld)**maturity\n\nprint("The price is", price)\n'

### Lists

####Introduction to Lists

abc

In [22]:
option_prices = [2.1, 1.2, 3.0, 4.2]
print(option_prices)
print(type(option_prices))

[2.1, 1.2, 3.0, 4.2]
<class 'list'>


In [23]:
#Creating a custom 1D list
cash_flows_1_Bond = [2, 2, 2, 102]
print("1: ",cash_flows_1_Bond)

cash_flows_2_Bond = [4, 4, 104, 0]
print("2: ",cash_flows_2_Bond)

cash_flows_3_Bond = [7, 7, 7, 107]
print("3: ",cash_flows_3_Bond)

cash_flows_Port_Bond = [cash_flows_1_Bond, cash_flows_2_Bond, cash_flows_3_Bond]
print("4: ",cash_flows_Port_Bond)

1:  [2, 2, 2, 102]
2:  [4, 4, 104, 0]
3:  [7, 7, 7, 107]
4:  [[2, 2, 2, 102], [4, 4, 104, 0], [7, 7, 7, 107]]


In [ ]:
#accessing the elements of 1D list
print("1: ",cash_flows_1_Bond[0])
print("2: ",cash_flows_2_Bond[2])
print("3: ",cash_flows_3_Bond[:2])
print("4: ",cash_flows_2_Bond[1:3])

1:  2
2:  104
3:  [7, 7]
4:  [4, 104]


In [ ]:
#accessing the elements of 2D list
print("1: ",cash_flows_Port_Bond[:])
print("2: ",cash_flows_Port_Bond[:][0:2])
print("3: ",cash_flows_Port_Bond[0:3])
print("4: ",cash_flows_Port_Bond[0:3][2])
print("5: ",cash_flows_Port_Bond[1:2])
print("6: ",cash_flows_Port_Bond[1:2][0])
#print(cash_flows_Port_Bond[1:2][1])  this will give an error

#to get a smaller aXb array from a bigger cXd array (where a<c, and b<d), a good choice is an array. Another case of numpy array

1:  [[2, 2, 2, 102], [4, 4, 104, 0], [7, 7, 7, 107]]
2:  [[2, 2, 2, 102], [4, 4, 104, 0]]
3:  [[2, 2, 2, 102], [4, 4, 104, 0], [7, 7, 7, 107]]
4:  [7, 7, 7, 107]
5:  [[4, 4, 104, 0]]
6:  [4, 4, 104, 0]


In [28]:
#creating sequential list through range
A = range(10)
print(A)

range(0, 10)


In [33]:
B = list(range(10))
print("1: ",B)

C = list(range(2,20,2))
#Need to be careful with the variables. In the below, the unintentional usage of "c" instead of "C" leads to unintended output. 
#This can go unnoticed in large programs where we dont print after every step 
#PYTHON IS A CASE SENSITIVE LANGUAGE
print("2: ",c)

#The correct variable is used below
print("3: ",C)

1:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
2:  Arpit
3:  [2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
#Strings typecasted as list will split the string into single characters
D = "My name is Arpit"
E = list(D) #We could have directly written D = list("My name is Arpit")
E

['M',
 'y',
 ' ',
 'n',
 'a',
 'm',
 'e',
 ' ',
 'i',
 's',
 ' ',
 'A',
 'r',
 'p',
 'i',
 't']

In [34]:
#Addition of list is stacking. This does not work as arithmetic operation. Case for the use of numpy array
X = B+B
print(X)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [36]:
#Performing element by element arithmetic operations results in an error. Case for the use numpy array
'''
Y = 2*B/5
print(Y)
'''

'\nY = 2*B/5\nprint(Y)\n'

####List Functions

Below are some of the common list functions in python. There are several others whose details can be found at https://www.programiz.com/python-programming/methods/list

In [37]:
#List Functions

#1. length of list
print("1: ",len(cash_flows_1_Bond))

#2. last element of list
print("2: ",cash_flows_1_Bond[-1])

#3. Append: to insert at the end
total_cashflow_portfolio = []
total_cashflow_portfolio.append(30)
print("3: ",total_cashflow_portfolio)
total_cashflow_portfolio.append(20)
print("4: ",total_cashflow_portfolio)
total_cashflow_portfolio.append(-10)
print("5: ",total_cashflow_portfolio)
total_cashflow_portfolio.append(40)
print("6: ",total_cashflow_portfolio)

#4. Insert: To insert at a specific location
total_cashflow_portfolio.insert(1,35)
print("7: ",total_cashflow_portfolio)

#5. Pop
total_cashflow_portfolio.pop(2) #pops the specific element
print("8: ",total_cashflow_portfolio)
total_cashflow_portfolio.pop() #pops the last element
print("9: ",total_cashflow_portfolio)

#6: Copy: 
##If you assign a list to a new variable and modify the new variable, the old list also gets modified
new_list = total_cashflow_portfolio
print("10: ", new_list)
new_list.append(70)
print("11: ", new_list)
print("12: ", total_cashflow_portfolio)

##To avoid this issue and retain the original list while modifying the new list, use list.copy
new_list_copy = list.copy(total_cashflow_portfolio)
print("13: ", new_list_copy)
new_list_copy.append(100)
print("14: ", new_list_copy)
print("15: ", total_cashflow_portfolio)


1:  4
2:  102
3:  [30]
4:  [30, 20]
5:  [30, 20, -10]
6:  [30, 20, -10, 40]
7:  [30, 35, 20, -10, 40]
8:  [30, 35, -10, 40]
9:  [30, 35, -10]
10:  [30, 35, -10]
11:  [30, 35, -10, 70]
12:  [30, 35, -10, 70]
13:  [30, 35, -10, 70]
14:  [30, 35, -10, 70, 100]
15:  [30, 35, -10, 70]


In [38]:
a = 10
b = a
b = b+10

print(b)
print(a)

20
10


##**Conditions**

###If Statement


In [46]:
#INDENTATION IS EXTREMELY IMPORTANT
vol = 0.2


if vol<0:
  print("Invalid input volatility. please enter again!!")

good_1
good


###If-else-statement

In [48]:
rate = 0.2

if rate<0:
  print("Negative rate")
else:
  print("Non-negative rate")

Non-negative rate


####If-elif-else Statement

Conditional operators include:

equals:   a == 10 (note that a=10 is an assignment operator)

not equal: a!=10

less than: a<10

less than equal to: a<=10

greater than: a>10

greater than equal to: a>=10

In [51]:
#We can have multiple elif between if and else
#Also, there could be if within an if => nested if

bond_ytm = 0.05
bond_coupon = 0.05

if(bond_coupon > bond_ytm):
  print("Premium Bond")
elif(bond_coupon < bond_ytm):
  print("Discount Bond")
else:
  print("Par Bond")



Par Bond


##**Loops**

###1. For loops

In [56]:
a = list(range(10))
print(a)

b = ['a','b','c']
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['a', 'b', 'c']


In [55]:
for i in a:
  print("Hello")
  print("Bye")

Hello
Bye
Hello
Bye
Hello
Bye
Hello
Bye
Hello
Bye
Hello
Bye
Hello
Bye
Hello
Bye
Hello
Bye
Hello
Bye


In [ ]:
#print squares from 0 to 9
for i in a:
  print(i*i)

0
1
4
9
16
25
36
49
64
81


Operations on custom list

In [ ]:
# Print square of each residual of OLS regression
residuals = [0.2, 0.4, -0.5, 0.3]
for i in residuals:
  print(i*i)

0.04000000000000001
0.16000000000000003
0.25
0.09


In [ ]:
# Print square of each residual assigning the index to the result and also print sum of square residuals of OLS regression
residuals = [0.2, 0.4, -0.5, 0.3]
sum = 0
cnt = 1

for i in residuals:
  print("Square Residual ", cnt, " = ", i*i)
  sum = sum + i*i
  cnt = cnt+1
print("Sum of square residual is", sum)

Square Residual  1  =  0.04000000000000001
Square Residual  2  =  0.16000000000000003
Square Residual  3  =  0.25
Square Residual  4  =  0.09
Sum of square residual is 0.54


In [74]:
# Create a list of squared residuals
square_residuals = []
residuals = [0.2, 0.4, -0.5, 0.3]

for i in residuals:
  square_residuals.append(i*i)

print(square_residuals) #make sure that the indentation is correct. If this is indented within the for loop, then the results will be printed four times

[0.04000000000000001, 0.16000000000000003, 0.25, 0.09]


###2. While Loop

In [57]:
#While loops may be used in optimization problems (with tolerance threshold in bisection)
initial_range = 40
tolerance = 0.02 

while (initial_range>tolerance):
  print("New Value = ", initial_range)
  initial_range = initial_range/2

print(initial_range)

New Value =  40
New Value =  20.0
New Value =  10.0
New Value =  5.0
New Value =  2.5
New Value =  1.25
New Value =  0.625
New Value =  0.3125
New Value =  0.15625
New Value =  0.078125
New Value =  0.0390625
0.01953125


##**User defined Functions**

In [64]:
#create a function for sum of first n numbers (user input is n):

def sum_first_num(n):
  sum = 0 #without initializing, it will through en error (UnboundLocalError: local variable 'sum' referenced before assignment)
  for i in range(n):
    sum = sum+ (i+1)
  return sum

In [67]:
a = sum_first_num(20)
b = a*a
print(b)

44100


In [68]:
#create a function for factorial

def fact_val(n):
  fact = 1
  for i in range(n):
    fact = fact*(i+1)
  return fact

In [72]:
second_order_coeff = 1/ fact_val(2)
second_order_coeff

0.5

##**Numpy Arrays**

In [75]:
square_residuals

[0.04000000000000001, 0.16000000000000003, 0.25, 0.09]

In [76]:
#calculate weighted square residuals (similar to stdev)
wt = [0.3, 0.3,0.2,0.2]

print(square_residuals)
print(wt)
print(type(square_residuals))
print(type(wt))

[0.04000000000000001, 0.16000000000000003, 0.25, 0.09]
[0.3, 0.3, 0.2, 0.2]
<class 'list'>
<class 'list'>


In [77]:
#The below multiplication is not allowed on lists. So, numpy arrays are used
#weighted_residuals = square_residuals * wt

TypeError: ignored

In [78]:
import numpy as np
square_residuals_array = np.array(square_residuals)
wt_array = np.array(wt)

print(square_residuals_array)
print(wt_array)
print(type(square_residuals_array))
print(type(wt_array))

[0.04 0.16 0.25 0.09]
[0.3 0.3 0.2 0.2]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [79]:
weighted_residuals = square_residuals_array*wt_array
print(weighted_residuals)

[0.012 0.048 0.05  0.018]


In [ ]:
#Cross Check of above result
[0.3*0.04, 0.3*0.16, 0.2*0.25, 0.2*0.09]

[0.012, 0.048, 0.05, 0.018]

In [81]:
sum_1 = weighted_residuals.sum()
print("Weighted Mean squared error is: ", sum_1)

Weighted Mean squared error is:  0.128
